### PR TITLE
Route PrometheusRuleFailures to null receiver

### PR DESCRIPTION
**Pull request by cblecker**
ref https://issues.redhat.com/browse/OHSS-2163
https://bugzilla.redhat.com/show_bug.cgi?id=1872786

### CODE REVIEW

**Comment by cblecker** [comment]
/hold
for review

**Comment by dofinn** [comment]
Looks like this sledge hammer is the only way forward to protect on call. 
/lgtm

**Comment by jewzaam** [comment]
Context for remove hold, +1 from me and others.  Discussion internal is basically "yes make this go away"

**Pull request merged**
