### PR TITLE
suppres curator failed jobs OSD-6348

### PR DESCRIPTION
**Pull request by dofinn**
Please refer to: https://issues.redhat.com/browse/OSD-6348

### CODE REVIEW

**Comment by cblecker** [comment]
/hold
for discussion

**Comment by cblecker** [comment]
similar to OSD-5544, going to replace this with a better tuned alert. once that alert is in place, we can push this too.

/approve

**Comment by dofinn** [comment]
/hold

Creating custom SRE rule in MCC
https://github.com/openshift/managed-cluster-config/pull/653/files

**Comment by dofinn** [comment]
closing. This alert is adequate. Being paged on it is not. Need to resolve this problem elsewhere

**Pull request closed without merging**
