### PR TITLE
Move alert ignore earlier in the func to actually work

### PR DESCRIPTION
**Pull request by mmazur**
This corrects #171 and should actually make the ignore work.

### CODE REVIEW

**Comment by georgettica** [comment]
I can 
/lgtm
but isn't there an order we need to enforce now to make this issue not happen even again
/hold
so we can discuss this

**Comment by fahlmant** [comment]
What's the reason it needed to be moved up to work?

**Comment by mmazur** [comment]
Seems to me the alert [example](https://redhat.pagerduty.com/incidents/PMPZ342) is getting caught by one of the rules below, which is why it's not working:

```
{Receiver: receiverPagerduty, MatchRE: map[string]string{"exported_namespace": alertmanager.PDRegex}, Match: map[string]string{"prometheus": "openshift-monitoring/k8s"}},
{Receiver: receiverPagerduty, MatchRE: map[string]string{"namespace": alertmanager.PDRegex}, Match: map[string]string{"exported_namespace": "", "prometheus": "openshift-monitoring/k8s"}},
{Receiver: receiverPagerduty, Match: map[string]string{"job": "fluentd", "prometheus": "openshift-monitoring/k8s"}},
```

hence this patch to correct it.

@georgettica I don't know what you're referring to.

**Comment by georgettica** [comment]
If this rule is caught by something else, is that a one off? Or should we invest time in making sure these things (metrics being caught by other regexes) will always work?

**Comment by RiRa12621** [comment]
I'd say that's a longer effort and should be carded up a follow up work

**Comment by mmazur** [comment]
Soooo....?

**Comment by RiRa12621** [comment]
As mentioned on slack before, please create the follow up card before we merge this.

**Comment by mmazur** [comment]
Done

**Pull request merged**
